mongodb:
  connection-string: "mongodb://127.0.0.1:27017/?replicaSet=rs0"
  database: "cryptocurrency"

plugin:
  prefix: "§f§l[§7§lC§8§lC§f§l] "
  enable: true
  verbose-logging: true

blockchain:
  mempool-limit-per-block: 10


mining-machine:
  delay-ticks: 20
  #このtickは↑による(↑が20(1秒)なら↓を60で1分毎保存)
  save-interval-mining-ticks: 60
