mongodb:
  connection-string: "mongodb://127.0.0.1:27017/?replicaSet=rs0"
  database: "cryptocurrency"

plugin:
  prefix: "§f§l[§7§lC§8§lC§f§l] "
  enable: true
  verbose-logging: true

blockchain:
  # 1/difficultyの確率で採掘成功する
  difficulty: 16
  mining-reward: 100000
  mempool-limit-per-block: 100

mining-machine:
  delay-ticks: 20
  save-interval-millis: 10000
