name: CryptocurrencyPluginMC
version: '${version}'

main: io.github.uttmangosteen.cryptocurrencyPluginMC.Main
api-version: '1.21'
load: POSTWORLD

commands:
  cryptocurrency:
    aliases: [ cc ] #CryptoCurrency
    usage: |
      §f§l========== §8§lCryptocurrency help §f§l==========
      §c§l× §f/cc wallet §7- 自分の財布を開く(GUI)
      
      §f/cc account create §7- 口座作成、財布に登録
      §f/cc account delete <index> §7- 財布から口座を削除 pubKeyを保存していなかったら、一生触れなくなる
      §f/cc account list §7- 財布に登録されている口座リスト
      §f/cc account main <index> §7- メイン口座を口座リストの中から切り替え
      §f/cc account memo <index> <memo> §7- 口座のメモを編集
      §f/cc account getPubKeyItem <index> [itemMemo] §7- 口座の公開鍵アイテムを取得、公開鍵指定用の補助アイテム
      §f/cc account getPrivateKeyItem <index> [itemMemo] §7- 口座の秘密鍵付き公開鍵アイテムを取得、§c取扱注意
      §f/cc account register [pubKey] §7- pubKey省略で手に持った鍵アイテムをWalletに登録する　pubKey平文指定も可
      
      
      §f/cc balance [index] §7- 口座の状況を確認
  
      §f/cc history [index] [page] §7- 口座の取引履歴を確認
  
      §f/cc send byName <amount> <name> §7- メイン口座から<name>の今のメイン口座への送金を一つ作成
      §f/cc send byPubKey <amount> [pubKey] §7- [pubKey]省略時、手に持った公開鍵アイテムへメイン口座からの送金を作成　[pubKey]を平文で指定もできるが、間違えた場合二度とお金は取り出せない
      §f/cc send list §7- 作成中の送金リスト
      §f/cc send delete <index|all> §7- 送金リストから間違えた送金を削除
      §f/cc send create <fee> [memo] §7- いまの送金リストをまとめてマイナー報酬を設定の上取引を作成 mempoolに登録 メモの長さは32文字まで
  
      §c§l× §f/cc info blockchain §7- blockchainの状況を確認
      §c§l× §f/cc info mempool §7- mempoolの状況を確認
      §f§l=========================================
    permission: cryptocurrency.user
  cryptocurrencymachine:
    aliases: [ ccmcn ] #CryptoCurrencyMaChiNe
    usage: |
      §f§l========== §8§lCryptocurrency Machine help §f§l==========
      §f/ccmcn create §7- 採掘機を作成
      §f/ccmcn remove <machineId> §7- 採掘機を撤去
  
      §f/ccmcn info <machineId> §7- 採掘機の情報を確認
  
      §c§l× §f/ccmcn open <machineId> §7- 採掘機を開く
      §f/ccmcn gpu <set|take> <machineId> <slot> §7- 採掘機のGPU設置/取り外し
      §f/ccmcn user <add|delete> <machineId> <name> §7- 採掘機に触れるユーザーの追加/削除
      §f/ccmcn toggle <machineId> §7- 採掘機の電源切り替え
      §f/ccmcn shareName <machineId> §7- 採掘成功時に、名前を共有するか切り替え
  
      §f/ccmcn fuel <machineId> §7- 手持ちの丸石を採掘機の燃料にする
      
      §f/ccmcn block setRewardPubKey <machineId> [index] §7- 自分のwalletの公開鍵を設定
      §f/ccmcn block setDefaultMemo <machineId> [memo] §7- 採掘ブロックのメモを設定しなかった場合のメモ設定
      §f/ccmcn block setMemo <machineId> [memo] §7- 採掘中ブロックのメモ設定
      §f/ccmcn block txMode <machineId> §7- 採掘ブロックのトランザクションの集め方切り替え
      §f/ccmcn block recreate <machineId> §7-最新のmempoolに合わせてブロックの再構築
      §f§l=================================================
    permission: cryptocurrency.miner
  cryptocurrencyadmin:
    aliases: [ ccop ]
    usage: |
      §f§l========== §8§lCryptocurrency Admin help §f§l==========
      §f/ccop <run|halt> §7- プラグインの停止/再開
      
      §f/ccop getGpu <gpuId> §7- GPUアイテム取得
      
      §c§l× §f/ccop database reconnect §7- データベース再接続
      §c§l× §f/ccop database flush §7- mempool等、消せる情報を消す(何かの移行時の圧縮用)
      §c§l× §f/ccop database rebuild §7- blocksコレクションからUTXOやTxHistoryなどのcash再計算(flushからの復旧)
      §f§l===============================================
    permission: cryptocurrency.admin

permissions:
  cryptocurrency.user:
    description: ユーザー用
    default: op
  cryptocurrency.miner:
    description: 採掘者用
    default: op
    children:
      cryptocurrency.user: true
  cryptocurrency.admin:
    description: OP用
    default: op
    children:
      cryptocurrency.miner: true